import { pgTable, serial, varchar, text, boolean, integer, decimal, timestamp } from 'drizzle-orm/pg-core';

export const cities = pgTable('cities', {
  id: serial('id').primaryKey(),
  slug: varchar('slug', { length: 100 }).unique().notNull(),
  name: varchar('name', { length: 100 }).notNull(),
  state: varchar('state', { length: 2 }).notNull(),
  county: varchar('county', { length: 100 }),
  region: varchar('region', { length: 50 }),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  h1Headline: text('h1_headline'),
  localHook: text('local_hook'),
  localLandmark: varchar('local_landmark', { length: 200 }),
  localChallenge: text('local_challenge'),
  housingType: varchar('housing_type', { length: 100 }),
  seasonalPeak: varchar('seasonal_peak', { length: 50 }),
  waterQualityNote: text('water_quality_note'),
  primaryCustomer: varchar('primary_customer', { length: 50 }),
  secondaryCustomer: varchar('secondary_customer', { length: 50 }),
  hasVacationRentals: boolean('has_vacation_rentals').default(false),
  hasGolfCommunity: boolean('has_golf_community').default(false),
  hasHoa: boolean('has_hoa').default(false),
  offersCarpet: boolean('offers_carpet').default(true),
  offersUpholstery: boolean('offers_upholstery').default(true),
  offersTileGrout: boolean('offers_tile_grout').default(true),
  offersAreaRugs: boolean('offers_area_rugs').default(true),
  offersWindow: boolean('offers_window').default(true),
  offersEzBreeze: boolean('offers_ez_breeze').default(true),
  offersHardwood: boolean('offers_hardwood').default(true),
  nearbyCities: text('nearby_cities'),
  targetKeywords: text('target_keywords'),
  canonicalUrl: text('canonical_url'),
  seoPriority: integer('seo_priority').default(5),
  revenueTier: varchar('revenue_tier', { length: 10 }),
  isActive: boolean('is_active').default(true),
  isPublished: boolean('is_published').default(false),
  reviewCount: integer('review_count').default(0),
  avgRating: decimal('avg_rating', { precision: 3, scale: 2 }).default('0.00'),
  featuredReview: text('featured_review'),
  featuredReviewer: varchar('featured_reviewer', { length: 100 }),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const services = pgTable('services', {
  id: serial('id').primaryKey(),
  slug: varchar('slug', { length: 100 }).unique().notNull(),
  name: varchar('name', { length: 100 }).notNull(),
  tagline: text('tagline'),
  description: text('description'),
  rfProcess: text('rf_process'),
  icon: varchar('icon', { length: 50 }),
  isActive: boolean('is_active').default(true),
});

export const cityServices = pgTable('city_services', {
  id: serial('id').primaryKey(),
  cityId: integer('city_id').references(() => cities.id),
  serviceId: integer('service_id').references(() => services.id),
  isAvailable: boolean('is_available').default(true),
  localCopy: text('local_copy'),
  promoActive: boolean('promo_active').default(false),
});

export const reviews = pgTable('reviews', {
  id: serial('id').primaryKey(),
  cityId: integer('city_id').references(() => cities.id),
  reviewerName: varchar('reviewer_name', { length: 100 }),
  rating: integer('rating'),
  reviewText: text('review_text'),
  serviceSlug: varchar('service_slug', { length: 100 }),
  source: varchar('source', { length: 50 }),
  isFeatured: boolean('is_featured').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});