import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { cities as citiesTable } from './schema';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const cities = [
  {
    slug: "salisbury-md",
    name: "Salisbury",
    state: "MD",
    county: "Wicomico County",
    region: "Eastern Shore",
    revenueTier: "A",
    seoPriority: 1,
    metaTitle: "Residue-Free Carpet Cleaning in Salisbury, MD | Tropical Breeze RF™",
    metaDescription: "Salisbury's original RF™ certified cleaning service. Carpet, upholstery, tile, hardwood, windows & EZ Breeze. No residue. 200+ 5-star reviews. Book today.",
    h1Headline: "Salisbury's Original Residue-Free Cleaning Company",
    localHook: "Born and built right here in Salisbury — the RF™ standard started on the Eastern Shore.",
    localLandmark: "Salisbury University / Downtown Plaza",
    localChallenge: "High-traffic family homes and rental properties near SU campus accumulate deep residue from repeated conventional cleaning",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Wicomico County tap water is moderately hard — mineral deposits accelerate residue buildup in carpet fibers",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: true,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Fruitland", "Delmar", "Parsonsburg", "Pittsville", "Bishopville"]),
    targetKeywords: JSON.stringify(["carpet cleaning Salisbury MD", "residue free carpet cleaning Salisbury", "upholstery cleaning Salisbury MD"]),
  },
  {
    slug: "ocean-city-md",
    name: "Ocean City",
    state: "MD",
    county: "Worcester County",
    region: "Beach Towns",
    revenueTier: "A",
    seoPriority: 1,
    metaTitle: "Vacation Rental Carpet Cleaning in Ocean City, MD | Tropical Breeze RF™",
    metaDescription: "Ocean City's RF™ cleaning specialists. Fast 4-6hr dry time for vacation rental turnovers. Same-day available. Call 443-856-3244.",
    h1Headline: "Ocean City's #1 Vacation Rental Cleaning Service",
    localHook: "Sand, salt air, and summer traffic — our RF™ process handles what the boardwalk sends home with your guests.",
    localLandmark: "Ocean City Boardwalk / Inlet",
    localChallenge: "Vacation rental turnovers demand fast dry times — traditional cleaning's 24-48hr drying window destroys turnover schedules",
    housingType: "vacation rentals / condos",
    seasonalPeak: "summer",
    waterQualityNote: "Coastal salt air accelerates fiber breakdown — RF™ low-moisture method reduces mold risk",
    primaryCustomer: "vacation_rental",
    secondaryCustomer: "property_manager",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: true,
    nearbyCities: JSON.stringify(["Berlin", "Ocean Pines", "Fenwick Island DE", "Bethany Beach DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Ocean City MD", "vacation rental cleaning Ocean City", "same day carpet cleaning Ocean City"]),
  },
  {
    slug: "rehoboth-beach-de",
    name: "Rehoboth Beach",
    state: "DE",
    county: "Sussex County",
    region: "Beach Towns",
    revenueTier: "A",
    seoPriority: 1,
    metaTitle: "Residue-Free Carpet Cleaning in Rehoboth Beach, DE | Tropical Breeze RF™",
    metaDescription: "RF™ certified carpet, upholstery & window cleaning in Rehoboth Beach. Vacation rental turnover specialists. 4-6hr dry time. Book now.",
    h1Headline: "Rehoboth Beach's Residue-Free Cleaning Specialists",
    localHook: "Salt air and sand don't stay at the beach — our RF™ process makes sure the residue doesn't either.",
    localLandmark: "Rehoboth Beach Boardwalk",
    localChallenge: "Sandy, salt-air environments accelerate fiber breakdown in vacation rental carpets and upholstery",
    housingType: "vacation rentals",
    seasonalPeak: "summer",
    waterQualityNote: "Coastal humidity accelerates mold risk — RF™ low-moisture method is critical in beach properties",
    primaryCustomer: "vacation_rental",
    secondaryCustomer: "property_manager",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Dewey Beach", "Lewes DE", "Bethany Beach DE", "Milton DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Rehoboth Beach DE", "vacation rental cleaning Rehoboth Beach", "residue free cleaning Rehoboth Beach"]),
  },
  {
    slug: "bethany-beach-de",
    name: "Bethany Beach",
    state: "DE",
    county: "Sussex County",
    region: "Beach Towns",
    revenueTier: "A",
    seoPriority: 1,
    h1Headline: "Bethany Beach's Residue-Free Cleaning Service",
    localHook: "Quiet Bethany deserves a clean that lasts — not one that re-soils before your next guests arrive.",
    localLandmark: "Bethany Beach Boardwalk",
    localChallenge: "High repeat vacation rental bookings — residue buildup between turnovers visibly affects guest satisfaction",
    housingType: "vacation rentals",
    seasonalPeak: "summer",
    waterQualityNote: "Coastal salt air environment — RF™ low-moisture approach critical",
    primaryCustomer: "vacation_rental",
    secondaryCustomer: "homeowner",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Fenwick Island DE", "Rehoboth Beach DE", "Ocean View DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Bethany Beach DE", "vacation rental cleaning Bethany Beach"]),
  },
  {
    slug: "fenwick-island-de",
    name: "Fenwick Island",
    state: "DE",
    county: "Sussex County",
    region: "Beach Towns",
    revenueTier: "A",
    seoPriority: 1,
    h1Headline: "Fenwick Island's Residue-Free Cleaning Specialists",
    localHook: "Where Delaware meets the Maryland line — RF™ cleaning that crosses borders and leaves zero residue behind.",
    localLandmark: "Fenwick Island State Park / Delaware-Maryland border",
    localChallenge: "High-density vacation rental corridor with rapid turnover windows",
    housingType: "vacation rentals",
    seasonalPeak: "summer",
    waterQualityNote: "Coastal barrier island — highest salt air exposure of all service cities",
    primaryCustomer: "vacation_rental",
    secondaryCustomer: "property_manager",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Bethany Beach DE", "Ocean City MD", "Selbyville DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Fenwick Island DE", "vacation rental cleaning Fenwick Island"]),
  },
  {
    slug: "lewes-de",
    name: "Lewes",
    state: "DE",
    county: "Sussex County",
    region: "Beach Towns",
    revenueTier: "A",
    seoPriority: 2,
    h1Headline: "Lewes, DE's Residue-Free Cleaning Specialists",
    localHook: "The First City of the First State gets Delaware's best cleaning standard — RF™, zero residue, every time.",
    localLandmark: "Cape Henlopen State Park / Historic Lewes waterfront",
    localChallenge: "Mix of historic homes and modern vacation rentals requiring inspection-first approach",
    housingType: "historic homes / vacation rentals",
    seasonalPeak: "summer",
    waterQualityNote: "Sussex County coastal — moderate humidity",
    primaryCustomer: "homeowner",
    secondaryCustomer: "vacation_rental",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Rehoboth Beach DE", "Milton DE", "Georgetown DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Lewes DE", "floor cleaning Lewes Delaware"]),
  },
  {
    slug: "the-peninsula-de",
    name: "The Peninsula",
    state: "DE",
    county: "Sussex County",
    region: "Golf Communities",
    revenueTier: "A",
    seoPriority: 1,
    h1Headline: "The Peninsula's Preferred Residue-Free Cleaning Service",
    localHook: "Jack Nicklaus Signature standards on the course — RF™ standards inside your home.",
    localLandmark: "Jack Nicklaus Signature course on Indian River Bay",
    localChallenge: "800-acre luxury community where HOA standards demand premium residue-free results",
    housingType: "golf community / luxury homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Bay-front humidity — low-moisture RF™ approach prevents mold in soft surfaces",
    primaryCustomer: "hoa",
    secondaryCustomer: "homeowner",
    hasVacationRentals: true,
    hasGolfCommunity: true,
    hasHoa: true,
    nearbyCities: JSON.stringify(["Millsboro DE", "Georgetown DE", "Lewes DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning The Peninsula DE", "golf community cleaning Delaware"]),
  },
  {
    slug: "bayside-de",
    name: "Bayside Resort",
    state: "DE",
    county: "Sussex County",
    region: "Golf Communities",
    revenueTier: "A",
    seoPriority: 1,
    h1Headline: "Bayside Resort's Residue-Free Cleaning Service",
    localHook: "Waterfront views on Assawoman Bay deserve windows and floors that match — streak-free, residue-free, every time.",
    localLandmark: "Assawoman Bay / Jack Nicklaus golf course",
    localChallenge: "Waterfront vacation homes require rapid turnovers — bay-view windows need streak-free EZ Breeze cleaning",
    housingType: "vacation rentals / golf community",
    seasonalPeak: "summer",
    waterQualityNote: "Waterfront bay location — high humidity demands RF™ low-moisture approach",
    primaryCustomer: "vacation_rental",
    secondaryCustomer: "property_manager",
    hasVacationRentals: true,
    hasGolfCommunity: true,
    hasHoa: true,
    nearbyCities: JSON.stringify(["Selbyville DE", "Fenwick Island DE", "Ocean City MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Bayside Resort DE", "EZ Breeze cleaning Bayside Delaware"]),
  },
  {
    slug: "heritage-shores-de",
    name: "Heritage Shores",
    state: "DE",
    county: "Sussex County",
    region: "Golf Communities",
    revenueTier: "A",
    seoPriority: 2,
    h1Headline: "Heritage Shores Residents Trust Tropical Breeze RF™",
    localHook: "Delaware's premier active adult community deserves a cleaning standard that's just as elevated — that's RF™.",
    localLandmark: "Heritage Shores championship golf course",
    localChallenge: "Permanent active adult residents with high standards who recommend or warn neighbors",
    housingType: "active adult community",
    seasonalPeak: "year-round",
    waterQualityNote: "Inland location — hard water mineral deposits in tile grout common",
    primaryCustomer: "homeowner",
    secondaryCustomer: "hoa",
    hasVacationRentals: false,
    hasGolfCommunity: true,
    hasHoa: true,
    nearbyCities: JSON.stringify(["Bridgeville DE", "Seaford DE", "Georgetown DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Heritage Shores DE", "cleaning service Heritage Shores Bridgeville"]),
  },
  {
    slug: "nutters-crossing-md",
    name: "Nutters Crossing",
    state: "MD",
    county: "Wicomico County",
    region: "Golf Communities",
    revenueTier: "A",
    seoPriority: 2,
    h1Headline: "Nutters Crossing Homeowners Choose Tropical Breeze RF™",
    localHook: "The Augusta of the North deserves a cleaning standard that matches its reputation — zero residue, every time.",
    localLandmark: "Nutters Crossing Golf Club",
    localChallenge: "Upscale Wicomico County home market — word-of-mouth drives repeat business",
    housingType: "golf community homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Wicomico County water — moderate hardness",
    primaryCustomer: "homeowner",
    secondaryCustomer: "hoa",
    hasVacationRentals: false,
    hasGolfCommunity: true,
    hasHoa: true,
    nearbyCities: JSON.stringify(["Salisbury MD", "Fruitland MD", "Delmar MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Nutters Crossing Salisbury MD", "golf community cleaning Wicomico County"]),
  },
  {
    slug: "berlin-md",
    name: "Berlin",
    state: "MD",
    county: "Worcester County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 3,
    h1Headline: "Berlin, MD's Residue-Free Cleaning Service",
    localHook: "Berlin's Main Street charm deserves a home that's just as clean — no residue, no re-soiling.",
    localLandmark: "Historic Downtown Berlin / Globe Theatre",
    localChallenge: "Older homes near the coast with original hardwood and older carpet",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Worcester County — coastal mineral content similar to Ocean City",
    primaryCustomer: "homeowner",
    secondaryCustomer: "vacation_rental",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Ocean City MD", "Ocean Pines MD", "Snow Hill MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Berlin MD", "residue free cleaning Berlin Maryland"]),
  },
  {
    slug: "ocean-pines-md",
    name: "Ocean Pines",
    state: "MD",
    county: "Worcester County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 3,
    h1Headline: "Ocean Pines Residents Trust Tropical Breeze RF™",
    localHook: "Ocean Pines HOA standards are high — our RF™ process keeps your home matching the community's reputation.",
    localLandmark: "Ocean Pines Golf Club / Yacht Club",
    localChallenge: "Established HOA community where property condition impacts community standing",
    housingType: "hoa community",
    seasonalPeak: "year-round",
    waterQualityNote: "Near-coastal — moderate humidity, EZ Breeze enclosures common",
    primaryCustomer: "homeowner",
    secondaryCustomer: "hoa",
    hasVacationRentals: false,
    hasGolfCommunity: true,
    hasHoa: true,
    nearbyCities: JSON.stringify(["Berlin MD", "Ocean City MD", "Bishopville MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Ocean Pines MD", "HOA cleaning Ocean Pines Maryland"]),
  },
  {
    slug: "cambridge-md",
    name: "Cambridge",
    state: "MD",
    county: "Dorchester County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 3,
    h1Headline: "Cambridge, MD's Residue-Free Cleaning Specialists",
    localHook: "Cambridge's waterfront revival deserves interiors that match — RF™ clean that lasts.",
    localLandmark: "Choptank River / Historic Downtown Cambridge",
    localChallenge: "Waterfront and historic homes with older flooring requiring inspection-first approach",
    housingType: "single family homes / historic",
    seasonalPeak: "year-round",
    waterQualityNote: "Dorchester County waterfront — humidity critical for carpet and hardwood",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Easton MD", "Salisbury MD", "Princess Anne MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Cambridge MD", "floor cleaning Cambridge Maryland"]),
  },
  {
    slug: "easton-md",
    name: "Easton",
    state: "MD",
    county: "Talbot County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 3,
    h1Headline: "Easton, MD's Residue-Free Cleaning Service",
    localHook: "The Colonial Capital of the Eastern Shore deserves a cleaning standard that's just as distinguished — that's RF™.",
    localLandmark: "Historic Easton Downtown / Avalon Theatre",
    localChallenge: "Mix of historic colonial homes and modern luxury properties — hardwood and tile inspection critical",
    housingType: "historic homes / luxury properties",
    seasonalPeak: "year-round",
    waterQualityNote: "Talbot County — varied water quality, older homes may have harder water",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["St. Michaels MD", "Cambridge MD", "Trappe MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Easton MD", "floor cleaning Easton Maryland"]),
  },
  {
    slug: "st-michaels-md",
    name: "St. Michaels",
    state: "MD",
    county: "Talbot County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 3,
    h1Headline: "St. Michaels, MD — Residue-Free Cleaning for Waterfront Homes",
    localHook: "The town that fooled the British deserves a cleaning service that doesn't fool you — RF™ leaves nothing behind.",
    localLandmark: "Chesapeake Bay Maritime Museum / Harbor",
    localChallenge: "Waterfront vacation rentals and historic B&Bs need fast turnovers without damaging antique hardwood",
    housingType: "vacation rentals / historic homes",
    seasonalPeak: "summer/fall",
    waterQualityNote: "Chesapeake Bay waterfront — high humidity, critical for hardwood moisture management",
    primaryCustomer: "vacation_rental",
    secondaryCustomer: "homeowner",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Easton MD", "Tilghman MD", "Oxford MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning St. Michaels MD", "vacation rental cleaning St Michaels Maryland"]),
  },
  {
    slug: "princess-anne-md",
    name: "Princess Anne",
    state: "MD",
    county: "Somerset County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 4,
    h1Headline: "Princess Anne, MD Residue-Free Cleaning Service",
    localHook: "Somerset County's oldest town deserves a cleaning service that's built for the long haul — RF™ clean that lasts.",
    localLandmark: "University of Maryland Eastern Shore / Historic District",
    localChallenge: "College town and family community — student rentals and family homes need deep cleaning after heavy use",
    housingType: "single family homes / rentals",
    seasonalPeak: "year-round",
    waterQualityNote: "Somerset County water — moderate hardness",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Salisbury MD", "Crisfield MD", "Snow Hill MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Princess Anne MD", "floor cleaning Somerset County MD"]),
  },
  {
    slug: "milton-de",
    name: "Milton",
    state: "DE",
    county: "Sussex County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 3,
    h1Headline: "Milton, DE Residue-Free Cleaning Service",
    localHook: "Milton is one of Delaware's fastest growing towns — RF™ is growing right alongside it.",
    localLandmark: "Dogfish Head Brewery / Milton Memorial Park",
    localChallenge: "Rapidly growing community with new construction — new carpet needs RF™ from day one",
    housingType: "single family homes / new construction",
    seasonalPeak: "year-round",
    waterQualityNote: "Sussex County — moderate water hardness",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Lewes DE", "Rehoboth Beach DE", "Georgetown DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Milton DE", "floor cleaning Milton Delaware"]),
  },
  {
    slug: "georgetown-de",
    name: "Georgetown",
    state: "DE",
    county: "Sussex County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 4,
    h1Headline: "Georgetown, DE Residue-Free Cleaning Service",
    localHook: "The seat of Sussex County deserves a cleaning standard that matches its importance — RF™.",
    localLandmark: "The Circle / Sussex County Courthouse",
    localChallenge: "County seat with mix of government workers, families, and rental properties",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Sussex County inland — moderate water hardness",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Lewes DE", "Milford DE", "Seaford DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Georgetown DE", "floor cleaning Sussex County Delaware"]),
  },
  {
    slug: "seaford-de",
    name: "Seaford",
    state: "DE",
    county: "Sussex County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 4,
    h1Headline: "Seaford, DE Residue-Free Cleaning Service",
    localHook: "The city that gave the world nylon deserves carpets that are treated right — RF™, zero residue.",
    localLandmark: "Nanticoke River / Historic Seaford District",
    localChallenge: "Older industrial-era homes with established carpet needing deep extraction",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Nanticoke River area — moderate water quality",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Bridgeville DE", "Delmar MD", "Georgetown DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Seaford DE", "floor cleaning Seaford Delaware"]),
  },
  {
    slug: "milford-de",
    name: "Milford",
    state: "DE",
    county: "Kent / Sussex County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 4,
    h1Headline: "Milford, DE Residue-Free Cleaning Service",
    localHook: "Milford sits right between two counties — RF™ serves both sides with the same zero-residue standard.",
    localLandmark: "Mispillion Riverwalk / Historic Downtown Milford",
    localChallenge: "Growing city on county border — new construction and older homes both in service area",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Kent/Sussex border — moderate water hardness",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Georgetown DE", "Lewes DE", "Dover DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Milford DE", "floor cleaning Kent County Delaware"]),
  },
  {
    slug: "fruitland-md",
    name: "Fruitland",
    state: "MD",
    county: "Wicomico County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 3,
    h1Headline: "Fruitland, MD Residue-Free Cleaning Service",
    localHook: "Fruitland is growing fast — your home deserves a cleaning service that keeps up. RF™ clean lasts 3x longer.",
    localLandmark: "Fruitland Community Park / Route 13 corridor",
    localChallenge: "Rapidly growing suburb with new construction and older homes",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Same Wicomico County water as Salisbury — moderate hardness",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Salisbury MD", "Delmar MD", "Pittsville MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Fruitland MD", "floor cleaning Fruitland Maryland"]),
  },
  {
    slug: "delmar-md-de",
    name: "Delmar",
    state: "MD",
    county: "Wicomico County / Sussex County",
    region: "Eastern Shore",
    revenueTier: "B",
    seoPriority: 3,
    h1Headline: "Delmar's Residue-Free Cleaning Service — Both Sides of the Line",
    localHook: "The Little Town Too Big for One State gets one cleaning standard that covers both sides — RF™.",
    localLandmark: "Maryland-Delaware state line running through Main Street",
    localChallenge: "Split-state community — residents on both sides need consistent service",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Wicomico / Sussex County border — moderate water hardness",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Salisbury MD", "Fruitland MD", "Seaford DE"]),
    targetKeywords: JSON.stringify(["carpet cleaning Delmar MD", "carpet cleaning Delmar DE"]),
  },
  {
    slug: "crisfield-md",
    name: "Crisfield",
    state: "MD",
    county: "Somerset County",
    region: "Eastern Shore",
    revenueTier: "C",
    seoPriority: 5,
    h1Headline: "Crisfield, MD Residue-Free Cleaning Service",
    localHook: "The Crab Capital of the World deserves a cleaning standard that's anything but ordinary — RF™ leaves zero residue.",
    localLandmark: "Tangier Sound / Working waterfront",
    localChallenge: "Working waterfront — seafood odors and heavy tracking require enzyme treatment and deep extraction",
    housingType: "single family homes",
    seasonalPeak: "summer",
    waterQualityNote: "Coastal waterfront — salt air and humidity management important",
    primaryCustomer: "homeowner",
    secondaryCustomer: "vacation_rental",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Princess Anne MD", "Snow Hill MD", "Pocomoke City MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Crisfield MD", "cleaning service Somerset County Maryland"]),
  },
  {
    slug: "snow-hill-md",
    name: "Snow Hill",
    state: "MD",
    county: "Worcester County",
    region: "Eastern Shore",
    revenueTier: "C",
    seoPriority: 5,
    h1Headline: "Snow Hill, MD Residue-Free Cleaning Service",
    localHook: "Small town. Big cleaning standards. RF™ is Snow Hill's residue-free choice.",
    localLandmark: "Pocomoke River / Historic Julia A. Purnell Museum",
    localChallenge: "Historic river town with older homes — careful surface inspection required",
    housingType: "single family homes / historic",
    seasonalPeak: "year-round",
    waterQualityNote: "Worcester County — Pocomoke River proximity, moderate water hardness",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Berlin MD", "Pocomoke City MD", "Princess Anne MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Snow Hill MD", "floor cleaning Worcester County MD"]),
  },
  {
    slug: "pocomoke-city-md",
    name: "Pocomoke City",
    state: "MD",
    county: "Worcester County",
    region: "Eastern Shore",
    revenueTier: "C",
    seoPriority: 5,
    h1Headline: "Pocomoke City's Residue-Free Cleaning Service",
    localHook: "The Friendliest Town on the Eastern Shore deserves a cleaning service with the same reputation — reliable, thorough, residue-free.",
    localLandmark: "Pocomoke River Canoe Trail / Cypress Park",
    localChallenge: "Pocomoke Swamp proximity means higher humidity — mold risk in carpets",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "High local humidity from Pocomoke Swamp — RF™ low-moisture approach especially important",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Snow Hill MD", "Princess Anne MD", "Salisbury MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Pocomoke City MD", "floor cleaning Worcester County Maryland"]),
  },
  {
    slug: "pittsville-md",
    name: "Pittsville",
    state: "MD",
    county: "Wicomico County",
    region: "Eastern Shore",
    revenueTier: "C",
    seoPriority: 5,
    h1Headline: "Pittsville, MD Residue-Free Cleaning Service",
    localHook: "Small community. Real clean. RF™ serves every home in Pittsville with the same standard as our biggest city jobs.",
    localLandmark: "Pittsville Community / Route 50 corridor",
    localChallenge: "Rural community — homes with well water may have higher mineral content",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Some homes on well water — higher mineral content accelerates residue bonding",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Salisbury MD", "Fruitland MD", "Parsonsburg MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Pittsville MD", "cleaning service Wicomico County MD"]),
  },
  {
    slug: "parsonsburg-md",
    name: "Parsonsburg",
    state: "MD",
    county: "Wicomico County",
    region: "Eastern Shore",
    revenueTier: "C",
    seoPriority: 5,
    h1Headline: "Parsonsburg, MD Residue-Free Cleaning Service",
    localHook: "Rural Wicomico County living deserves a cleaning service that comes to you — RF™ does.",
    localLandmark: "Parsonsburg community / Rural Wicomico County",
    localChallenge: "Rural community with well water and older housing stock",
    housingType: "single family homes / rural",
    seasonalPeak: "year-round",
    waterQualityNote: "Well water common — highest mineral content in service area",
    primaryCustomer: "homeowner",
    secondaryCustomer: "property_manager",
    hasVacationRentals: false,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Salisbury MD", "Pittsville MD", "Fruitland MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Parsonsburg MD", "cleaning service Wicomico County rural MD"]),
  },
  {
    slug: "bishopville-md",
    name: "Bishopville",
    state: "MD",
    county: "Worcester County",
    region: "Eastern Shore",
    revenueTier: "C",
    seoPriority: 5,
    h1Headline: "Bishopville, MD Residue-Free Cleaning Service",
    localHook: "Between Salisbury and the beach — RF™ brings the same standard to Bishopville that Ocean City expects.",
    localLandmark: "Route 50 corridor / near Ocean City",
    localChallenge: "Transitional community between suburban Salisbury and coastal Ocean City",
    housingType: "single family homes",
    seasonalPeak: "year-round",
    waterQualityNote: "Worcester County — similar to Berlin/Ocean City water quality",
    primaryCustomer: "homeowner",
    secondaryCustomer: "vacation_rental",
    hasVacationRentals: true,
    hasGolfCommunity: false,
    hasHoa: false,
    nearbyCities: JSON.stringify(["Berlin MD", "Ocean Pines MD", "Salisbury MD"]),
    targetKeywords: JSON.stringify(["carpet cleaning Bishopville MD", "cleaning service Worcester County MD"]),
  },
];

async function seed() {
  console.log("🌴 Seeding Tropical Breeze RF™ city database...");
  
  for (const city of cities) {
    await db.insert(citiesTable).values({
      ...city,
      canonicalUrl: `https://tropicalbreezerf.com/${city.slug}`,
      isActive: true,
      isPublished: false,
    }).onConflictDoNothing();
    console.log(`✅ Seeded: ${city.name}, ${city.state}`);
  }

  console.log(`\n🏁 Done. ${cities.length} cities seeded.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});